### PR TITLE
chore(lib/netconf): add omega static artefacts

### PR DESCRIPTION
**Pull request by pavelnikolov**
Add omega static artefacts.

issue: none

### CODE REVIEW

**Comment by arajasek** [comment]
Maybe close this since we've already reset the network?

**Comment by pavelnikolov** [comment]
I'll update it now

**Comment by pavelnikolov** [comment]
Updated to reflect latest omega deployment

**Comment by pavelnikolov** [comment]
Updated

**Review by corverroos — APPROVED** [review]

**Pull request merged**
