### PR TITLE
feat(explorer/graphql): search

### PR DESCRIPTION
**Pull request by DanFlannel**
Search by txhash and source address

- Blocks (by block has)
- Message (by txhash)
- Receipt (by txhash)

task: https://app.asana.com/0/1206208509925075/1206971960504979

### CODE REVIEW

**Comment by DanFlannel** [comment]
Still a little bit of a WIP, need to make result type an enum and verify these are the fields we want to be searching against, as well as verify they are fields we are indexing

**Review by kevinhalliday — APPROVED** [review]
Do we think we still need this now?

**Comment by DanFlannel** [comment]
I'm thinking we might for a v2, probably want to ask Fab about this first

**Comment by DanFlannel** [comment]
Just going to merge this today, most likely we will be integrating this feature in the near term

**Pull request merged**
