### PR TITLE
chore(contracts): fix comment typos

### PR DESCRIPTION
**Pull request by gabrielstoica**
Fix typos in the OmniAVS.sol and XTypes.sol comments

task: none

### CODE REVIEW

**Review by kevinhalliday — APPROVED** [review]
Thanks! Please rebase from main

**Comment by kevinhalliday** [comment]
@gabrielstoica oops -  we require [signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). if you could set that up and and sign these commits. or just reset into a single commit and sign it

**Comment by kevinhalliday** [comment]
All commits need to be signed - I'd just squash into a single commit and force push

**Comment by gabrielstoica** [comment]
@kevinhalliday should be good now.

**Comment by gabrielstoica** [comment]
Let's try now, @kevinhalliday

**Pull request merged**
