### PR TITLE
chore(contracts): store array length in local vars

### PR DESCRIPTION
**Pull request by rokso**
Store array length in local variable in solidity contracts to save gas.

task: none

### CODE REVIEW

**Comment by rokso** [comment]
Resolved conflicts.

**Review by pavelnikolov — APPROVED** [review]

**Comment by pavelnikolov** [comment]
@kevinhalliday LGTM, but I'm not going to run the workflow - will leave that to you.

**Review by kevinhalliday — CHANGES_REQUESTED** [review]
Thanks for the contribution. 

IMO this is a small sacrifice in readablity for smaller savings in gas costs. Generally, I think we should prefer readability, particularly at this stage in development. 

But `xsubmit` is a fine place to save some gas. So let's do it.

Please rename `_length` variable in each place to something more descriptive, so when we see it used later we know what it means.

For example, looking at this loop on it's own at the bottom of the function, it's not immediately clear what we are looping over.

```
  for (uint256 i = 0; i < _length; i++) {
      // ...
  }
```

**Comment by rokso** [comment]
@kevinhalliday I have renamed variable.

**Review by kevinhalliday — COMMENTED** [review]
Shorten to `numMsgs` and `numVals`?

Our pattern is no underscore prefix needed for local variables

**Comment by rokso** [comment]
> Shorten to `numMsgs` and `numVals`?
> 
> Our pattern is no underscore prefix needed for local variables

Sure I can do that.

**Comment by rokso** [comment]
> Shorten to `numMsgs` and `numVals`?
> 
> Our pattern is no underscore prefix needed for local variables

@kevinhalliday Done

**Review by kevinhalliday — APPROVED** [review]

**Pull request merged**
